version: "3"
services:
  vscode-container:
    image: mcr.microsoft.com/devcontainers/typescript-node
    #image: mcr.microsoft.com/devcontainers/base:debian
    #image: mcr.microsoft.com/devcontainers/base:alpine
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace
      - ~/.ssh:/home/node/.ssh
    env_file: devcontainer.env